version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto

  subscriber:
    build: ./subscriber
    container_name: subscriber
    depends_on:
      - mongo
      - mosquitto
    volumes:
      - ./subscriber:/app
